---
name: Lint Shell Scripts

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  shellcheck:
    name: ShellCheck Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Run ShellCheck Lint Engine
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: '.'
          severity: error
